
import React, { forwardRef } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Employee, SalaryReport } from "@/types";
import { useAppContext } from "@/context/AppContext";

interface PaytmReceiptProps {
  salaryReport: SalaryReport;
}

export const PaytmReceipt = forwardRef<HTMLDivElement, PaytmReceiptProps>(
  ({ salaryReport }, ref) => {
    const { employees, user } = useAppContext();
    const employee = employees.find((e) => e.id === salaryReport.employeeId);

    if (!employee) {
      return <div>Employee not found</div>;
    }

    const monthName = new Date(0, salaryReport.month - 1).toLocaleString('default', { month: 'long' });
    
    return (
      <div ref={ref} className="bg-white p-6 max-w-4xl mx-auto">
        <div className="border border-gray-200 rounded-lg overflow-hidden shadow-lg">
          {/* Receipt Header */}
          <div className="bg-gradient-to-r from-purple-500 to-indigo-600 text-white p-6">
            <div className="flex justify-between items-center">
              <div>
                <h1 className="text-3xl font-bold">{user.company || "AttendPay"}</h1>
                <p className="opacity-80 mt-1">Salary Receipt</p>
              </div>
              <div className="text-right">
                <p className="text-lg font-semibold">Reference #</p>
                <p className="text-xl font-mono">{salaryReport.employeeId.substring(0, 8)}</p>
              </div>
            </div>
          </div>
          
          {/* Employee Details */}
          <div className="p-6 bg-gray-50 border-b border-gray-200">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <h2 className="text-lg font-semibold text-gray-700">Employee Details</h2>
                <div className="mt-2 space-y-1">
                  <p><span className="font-medium">Name:</span> {employee.name}</p>
                  <p><span className="font-medium">Position:</span> {employee.position}</p>
                  <p><span className="font-medium">ID:</span> {employee.employeeIdNumber || "N/A"}</p>
                  <p><span className="font-medium">Email:</span> {employee.email}</p>
                </div>
              </div>
              <div>
                <h2 className="text-lg font-semibold text-gray-700">Payment Details</h2>
                <div className="mt-2 space-y-1">
                  <p><span className="font-medium">Period:</span> {monthName} {salaryReport.year}</p>
                  <p><span className="font-medium">Working Days:</span> {salaryReport.workDays}</p>
                  <p><span className="font-medium">Daily Rate:</span> ${employee.dailySalary.toFixed(2)}</p>
                  <p><span className="font-medium">Payment Date:</span> {new Date().toLocaleDateString()}</p>
                </div>
              </div>
            </div>
          </div>
          
          {/* Salary Breakdown */}
          <div className="p-6">
            <h2 className="text-xl font-bold text-gray-800 mb-4">Salary Breakdown</h2>
            <div className="bg-gray-50 rounded-md p-4 mb-6">
              <div className="flex justify-between py-2 border-b border-gray-200">
                <span className="font-medium">Base Salary ({salaryReport.workDays} days)</span>
                <span>${salaryReport.totalSalary.toFixed(2)}</span>
              </div>
              <div className="flex justify-between py-2 border-b border-gray-200">
                <span className="font-medium">Bonus</span>
                <span>$0.00</span>
              </div>
              <div className="flex justify-between py-2 border-b border-gray-200">
                <span className="font-medium">Deductions</span>
                <span>$0.00</span>
              </div>
              <div className="flex justify-between py-4 font-bold text-lg">
                <span>Total Amount</span>
                <span className="text-purple-700">${salaryReport.totalSalary.toFixed(2)}</span>
              </div>
            </div>
          </div>
          
          {/* Footer */}
          <div className="bg-gray-100 p-6 text-center text-gray-600 text-sm border-t border-gray-200">
            <p>This is an electronically generated receipt and does not require a signature.</p>
            <p className="mt-2">Generated by AttendPay on {new Date().toLocaleString()}</p>
          </div>
        </div>
      </div>
    );
  }
);

PaytmReceipt.displayName = "PaytmReceipt";
